language = "C"
no_includes = true
style = "both"            # <— important: emits `typedef enum Name { … } Name;`

[parse]
parse_deps = false

[export]
include = ["DataType", "DataEndpoint", "TelemetryErrorCode"]

[enum]
rename_variants = "ScreamingSnakeCase"
